
name: 'vgg16'
feature_layers: [
    'block1_conv1', 'block1_conv2', 'block2_conv1', 'block2_conv2', 
    'block3_conv1', 'block3_conv2', 'block3_conv3', 'block4_conv1', 
    'block4_conv2', 'block4_conv3', 'block5_conv1', 'block5_conv2',
    'block5_conv3'
]
batch_size: 32
seed: 42
augmentation: False
normalization: False