name : 'vgg16'
# Name of the last layer we freeze (included)
up_to_freeze: 'block2_conv2'
# Name of the pre-trained model layers we initialzie random
random_layers: []
# List of dense layers units to create. If empty, we will use the pre-trained model FC previous to classification
dense_list: [512, 512]
batch_norm: True
dropout: 0.3
lr: 0.0001
lr_decay: False
batch_size: 64
activation: 'relu'
augmentation: False
patience: 5
epochs: 30
seed: 42
# True means using pre-trained model preprocessing function. False means dividing by 255
normalization: False
label_smoothing: 0.5